### ISSUE TITLE
FRESH INSTALLATION

### ISSUE THREAD

**Issue by b6024636** [b6016323/Groak-Theme#11]
A theme activation is not working properly???? FIX?!

**Comment by b6016323** [comment]
Can you please explain what is happening?
What browser and environment are you testing it in?

**Comment by b6024636** [comment]
INTernet explorer.... Thank you fo rthe speedy reply :DD even so... thiS IS NOT! EXCEPTABLE

**Comment by b6016323** [comment]
Please leave me and my git alone

**Comment by b6024636** [comment]
Update: Problem seems to have been solved...
